"""
Medical RAG App
- Retrieval: our fine-tuned domain embedding model (trained from scratch
  on MedQuAD medical Q&A pairs, see /embedding_model)
- Generation: Groq API free tier (llama-3.1-8b-instant by default)

Run with:
    streamlit run app.py
"""
import os
import sys

import streamlit as st

sys.path.insert(0, os.path.dirname(__file__))
from retriever import MedicalRetriever  # noqa: E402
from generator import generate_answer, DEFAULT_MODEL  # noqa: E402

st.set_page_config(page_title="Medical RAG Assistant", page_icon="🩺", layout="wide")


@st.cache_resource
def load_retriever():
    return MedicalRetriever()


def main():
    st.title("🩺 Medical RAG Assistant")
    st.caption(
        "Retrieval powered by a domain embedding model trained from scratch on "
        "MedQuAD. Answers generated by Groq (free tier) grounded strictly in "
        "retrieved passages."
    )

    st.warning(
        "⚠️ Educational demo only. Not a substitute for professional medical "
        "advice, diagnosis, or treatment. Always consult a qualified clinician.",
        icon="⚠️",
    )

    with st.sidebar:
        st.header("Settings")
        api_key = st.text_input(
            "Groq API Key",
            value=os.environ.get("GROQ_API_KEY", ""),
            type="password",
            help="Free key: https://console.groq.com -> API Keys",
        )
        model = st.selectbox(
            "Groq model",
            ["llama-3.1-8b-instant", "llama-3.3-70b-versatile"],
            index=0,
        )
        top_k = st.slider("Passages to retrieve", 1, 10, 5)
        st.divider()
        st.caption(
            "Model names and free-tier limits change on Groq's side over time. "
            "Check console.groq.com if a model errors out."
        )

    query = st.text_input(
        "Ask a medical question",
        placeholder="e.g. What are the symptoms of Paget's disease of bone?",
    )

    if st.button("Ask", type="primary") and query:
        retriever = load_retriever()

        with st.spinner("Retrieving relevant medical passages..."):
            results = retriever.search(query, top_k=top_k)

        with st.spinner("Generating grounded answer via Groq..."):
            try:
                answer = generate_answer(
                    query, results, model=model, api_key=api_key or None
                )
            except Exception as e:
                st.error(f"Generation failed: {e}")
                answer = None

        if answer:
            st.subheader("Answer")
            st.markdown(answer)

        st.subheader("Retrieved sources")
        for i, r in enumerate(results, start=1):
            with st.expander(f"[{i}] {r['focus']}  ·  similarity {r['score']:.3f}"):
                st.markdown(f"**Q:** {r['question']}")
                st.markdown(f"**A:** {r['answer']}")
                st.caption(f"Source: {r['source']}  |  {r['url']}")


if __name__ == "__main__":
    main()
